// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvZuQmX0rKDonL7P7pfRLCiyfk8fmcadw',
    appId: '1:514784645652:web:ccb0ea047250a480e10d01',
    messagingSenderId: '514784645652',
    projectId: 'graduation-thesis-8b064',
    authDomain: 'graduation-thesis-8b064.firebaseapp.com',
    storageBucket: 'graduation-thesis-8b064.appspot.com',
    measurementId: 'G-Y292BS990T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCnZFuIWjq8Let1ayBDhyR6P6aqOdqWN74',
    appId: '1:514784645652:android:3589209c67d64495e10d01',
    messagingSenderId: '514784645652',
    projectId: 'graduation-thesis-8b064',
    storageBucket: 'graduation-thesis-8b064.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9jdoVWUit5VaSLjEPhOGUhqpukc_QAKg',
    appId: '1:514784645652:ios:81c0b452c6f67c24e10d01',
    messagingSenderId: '514784645652',
    projectId: 'graduation-thesis-8b064',
    storageBucket: 'graduation-thesis-8b064.appspot.com',
    iosBundleId: 'com.example.untitled1',
  );
}
